### ISSUE TITLE
sbt import not working

### ISSUE THREAD

**Issue by colomain** [suprnation/cats-actors#2]
Working sbt config:

```
resolvers += "jitpack" at "https://jitpack.io"

libraryDependencies += "com.github.suprnation" % "cats-actors" % "v1.0.2"
```

If you look a build log (https://jitpack.io/com/github/suprnation/cats-actors/v1.0.2/build.log) you will see that it's not scala version dependent (no 2.13 in url) and tag version is `v1.0.2`, not `1.0.2`

I guess maven and other install configurations are falling too... but I haven't checked

**Comment by jducoeur** [comment]
Huh -- I'm quite surprised that it's not Scala version dependent...

**Comment by cloudmark** [comment]
I will check later, I'm using jitpack purely to make it simple for people to download artifacts from github (maybe that skewed these things up).  The plan is to upload to maven central shortly .

**Comment by cloudmark** [comment]
Confirmed @colomain, this should be as you suggested, I am going to release an update for typed actors and make sure that the URL is correct.  

Thank you
