### ISSUE TITLE
Dependency does not exist in jitpack

### ISSUE THREAD

**Issue by PowerfulHokko** [suprnation/cats-actors#4]
https://jitpack.io/com/github/suprnation/cats-actors/cats-actors_3/v2.0.0-RC2/cats-actors_3-v2.0.0-RC2.pom returns 404.
Sorry if the explanation is quite short, but the dependency doesn't resolve so I cannot use it.

**Comment by cloudmark** [comment]
sorry about that the import should be 2.0.0-RC2 and not v2.0.0-RC2

See: 
https://jitpack.io/com/github/suprnation/cats-actors/2.0.0-RC2/cats-actors-2.0.0-RC2.pom

Can you please confirm if it works, I can try it out later.

**Comment by cloudmark** [comment]
It is listed correctly in the README.md, this pom.xml should work 

```
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>example-project</artifactId>
    <version>1.0-SNAPSHOT</version>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.suprnation.cats-actors</groupId>
            <artifactId>cats-actors_3</artifactId>
            <version>2.0.0-RC2</version>
        </dependency>
    </dependencies>
</project>
```

Closing the issue, please re-open if you experience any issues.

**Comment by PowerfulHokko** [comment]
That indeed solves it; the tag is wrong on jitpack, thanks for solving

**Comment by cloudmark** [comment]
Could you perhaps point me where you saw that tag please?

**Comment by PowerfulHokko** [comment]
When going to Jitpack (https://jitpack.io/#suprnation/cats-actors)
Click on "get it" next to: v2.0.0-RC2
Look at the given import on step 2.

libraryDependencies += "com.github.suprnation" % "cats-actors" % "v2.0.0-RC2"	

I think it's an error in jitpack, because if you change the url to: https://jitpack.io/#suprnation/cats-actors_3/2.0.0-RC2
That works fine, but that url isn't displayed anywhere.
